### ISSUE TITLE
Task View running in background extends session to infinite time.

### ISSUE THREAD

**Issue by xplicit** [orangehill/bootstrap-session-timeout#19]
Please look at this issue http://stackoverflow.com/questions/17818493/mousemove-event-repeating-every-second

If use bootstrap-session-timeout and open task manager on the background, the session will never be ended. The answer recommends to check `x` an `y` location of mouse pointer and if it's not changed does not extend timeout.

**Comment by vedraan** [comment]
I was able to reproduce the issue and the problem is with Chrome implementation of mousemove: https://code.google.com/p/chromium/issues/detail?id=241476 and isn't really related to the task manager since it's happening every time. What's strange is that when the plugin was developed this wasn't the case so the issue probably resurfaced in some later version of Chrome. As recommended we will add x/y position validation to fix this.

**Comment by xplicit** [comment]
It's not only chrome issue. IE10 IE11 have the same behaviour (when the task manager is opened in the background).

**Comment by vedraan** [comment]
Were you able to reproduce using version 1.03?
